/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/myCharacter.glb -o src/components/Character/Character.tsx -r public 
*/

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

export function MagGlass(props: any) {
  const character = useRef();

  const { scene } = useGLTF('/models/magGlass.glb');
  console.log(scene);
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);

  return (
    <group
      {...props}
      position={[4.5, -10, 1]}
      dispose={null}
      rotation={[0.1, 3.14, -0.9]}
      scale={0.025}
    >
      <primitive object={clone} ref={character} />
    </group>
  );
}

useGLTF.preload('/models/magGlass.glb');
