/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/myCharacter.glb -o src/components/Character/Character.tsx -r public 
*/

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

export function MagGlass(props: any) {
  const character = useRef();

  const { scene } = useGLTF('/models/magG.glb');
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);

  return (
    <group
      {...props}
      position={[2, -9, 3.6]}
      dispose={null}
      rotation={[3.9, 2.8, -2.5]}
      scale={12}
    >
      <primitive object={clone} ref={character} />
    </group>
  );
}

useGLTF.preload('/models/magG.glb');
